SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `Umfrage` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE `Umfrage`;

DROP TABLE IF EXISTS `Antworten`;
CREATE TABLE IF NOT EXISTS `Antworten` (
`AID` int(10) NOT NULL,
  `Text` text COLLATE utf8_bin NOT NULL,
  `Zähler` int(10) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `beantwortet`;
CREATE TABLE IF NOT EXISTS `beantwortet` (
  `UmID` int(11) NOT NULL,
  `UsID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `besitzt`;
CREATE TABLE IF NOT EXISTS `besitzt` (
  `AID` int(10) NOT NULL,
  `UID` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `Umfrage`;
CREATE TABLE IF NOT EXISTS `Umfrage` (
`UID` int(10) NOT NULL,
  `Frage` text COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `Users`;
CREATE TABLE IF NOT EXISTS `Users` (
`UID` int(11) NOT NULL,
  `username` text COLLATE utf8_bin NOT NULL,
  `password` text COLLATE utf8_bin NOT NULL,
  `email` text COLLATE utf8_bin NOT NULL,
  `vkey` text COLLATE utf8_bin NOT NULL,
  `valid` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


ALTER TABLE `Antworten`
 ADD PRIMARY KEY (`AID`);

ALTER TABLE `Umfrage`
 ADD PRIMARY KEY (`UID`);

ALTER TABLE `Users`
 ADD PRIMARY KEY (`UID`);


ALTER TABLE `Antworten`
MODIFY `AID` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=0;
ALTER TABLE `Umfrage`
MODIFY `UID` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=0;
ALTER TABLE `Users`
MODIFY `UID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=0;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
